// <auto-generated />
using System;
using JobService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobService.Infrastructure.Migrations
{
    [DbContext(typeof(JobServiceDbContext))]
    [Migration("20260604085819_AddJobNotes")]
    partial class AddJobNotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobService.Domain.Entities.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AssignedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancellationDescription")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceRegistryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EstimatedRemainingDistance")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingModes")
                        .HasColumnType("jsonb");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.PrimitiveCollection<string[]>("PreviousRobotOrderIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ProgressionRate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("QueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReassignedDeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReassignedDeviceRegistryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReassignmentCount")
                        .HasColumnType("integer");

                    b.Property<string>("RobotOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedByOrderTrackingOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("JobService.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AutomationChainingId")
                        .HasColumnType("integer");

                    b.Property<Guid>("AutomationId")
                        .HasColumnType("uuid");

                    b.Property<string>("AutomationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("JobPriority")
                        .HasColumnType("integer");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobService.Domain.Entities.OrderInstructions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actions")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ExecutionSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Goal")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("InstructionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ParentInstructionId")
                        .HasColumnType("integer");

                    b.Property<bool>("Reachable")
                        .HasColumnType("boolean");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemActions")
                        .HasColumnType("jsonb");

                    b.Property<int?>("SystemOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("UpdateOrderConditions")
                        .HasColumnType("jsonb");

                    b.Property<string>("WayPoints")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("ParentInstructionId");

                    b.HasIndex("SystemOrderId");

                    b.ToTable("OrderInstructions");
                });

            modelBuilder.Entity("JobService.Domain.Entities.SystemOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BundleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CancellationDescription")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("CancellationReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceRegistryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Errors")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EstimatedEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("EstimatedRemainingDistance")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("OperatingModes")
                        .HasColumnType("jsonb");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProgressionRate")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedByOrderTrackingOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SystemOrders");
                });

            modelBuilder.Entity("JobService.Domain.Entities.CustomerOrder", b =>
                {
                    b.HasOne("JobService.Domain.Entities.Job", "Job")
                        .WithMany("CustomerOrders")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobService.Domain.Entities.OrderInstructions", b =>
                {
                    b.HasOne("JobService.Domain.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("OrderInstructions")
                        .HasForeignKey("CustomerOrderId");

                    b.HasOne("JobService.Domain.Entities.OrderInstructions", "ParentInstruction")
                        .WithMany("Children")
                        .HasForeignKey("ParentInstructionId");

                    b.HasOne("JobService.Domain.Entities.SystemOrder", "SystemOrder")
                        .WithMany("OrderInstructions")
                        .HasForeignKey("SystemOrderId");

                    b.Navigation("CustomerOrder");

                    b.Navigation("ParentInstruction");

                    b.Navigation("SystemOrder");
                });

            modelBuilder.Entity("JobService.Domain.Entities.CustomerOrder", b =>
                {
                    b.Navigation("OrderInstructions");
                });

            modelBuilder.Entity("JobService.Domain.Entities.Job", b =>
                {
                    b.Navigation("CustomerOrders");
                });

            modelBuilder.Entity("JobService.Domain.Entities.OrderInstructions", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("JobService.Domain.Entities.SystemOrder", b =>
                {
                    b.Navigation("OrderInstructions");
                });
#pragma warning restore 612, 618
        }
    }
}
